// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBOD7-CL9qLHX21ozPsRQLPEZS9nD0bY0',
    appId: '1:569126850307:web:fe3e4fcfa4d71acccf6336',
    messagingSenderId: '569126850307',
    projectId: 'notifications-76a90',
    authDomain: 'notifications-76a90.firebaseapp.com',
    storageBucket: 'notifications-76a90.appspot.com',
    measurementId: 'G-TCZ4W6FQ83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKSPRp2d_zskD1Oz69SWBjo-mkgFcncV0',
    appId: '1:569126850307:android:032bdafddce8c9d2cf6336',
    messagingSenderId: '569126850307',
    projectId: 'notifications-76a90',
    storageBucket: 'notifications-76a90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6zUdGmlOqmCSMuO1AuQa4TtcCIWYSZeE',
    appId: '1:569126850307:ios:451edd3f57491811cf6336',
    messagingSenderId: '569126850307',
    projectId: 'notifications-76a90',
    storageBucket: 'notifications-76a90.appspot.com',
    iosBundleId: 'usman.notification.notifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6zUdGmlOqmCSMuO1AuQa4TtcCIWYSZeE',
    appId: '1:569126850307:ios:a6a31cb244cc498fcf6336',
    messagingSenderId: '569126850307',
    projectId: 'notifications-76a90',
    storageBucket: 'notifications-76a90.appspot.com',
    iosBundleId: 'usman.notification.notifications.RunnerTests',
  );
}
